<a href="https://colab.research.google.com/github/Mannem23/CodeOrbit-Internship/blob/main/Task1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving CodeOrbit_Task1_Raw_Dataset_500x10.xlsx to CodeOrbit_Task1_Raw_Dataset_500x10.xlsx

In [ ]:
import pandas as pd

df = pd.read_excel("CodeOrbit_Task1_Raw_Dataset_500x10.xlsx")

print("Dataset loaded successfully!")

Dataset loaded successfully!

In [ ]:
# STEP 2: DATA INSPECTION

print("===== DATASET SHAPE =====")
print("Rows and Columns:", df.shape)

print("\n===== COLUMN NAMES =====")
print(df.columns.tolist())

print("\n===== FIRST 5 ROWS =====")
display(df.head())

print("\n===== LAST 5 ROWS =====")
display(df.tail())

print("\n===== DATASET INFORMATION =====")
df.info()

===== DATASET SHAPE =====
Rows and Columns: (500, 10)

===== COLUMN NAMES =====
['Order_ID', 'Customer_Name', 'City', 'Category', 'Product', 'Order_Date', 'Quantity', 'Sales_Amount', 'Payment_Method', 'Order_Status']

===== FIRST 5 ROWS =====

,Order_ID,Customer_Name,City,Category,Product,Order_Date,Quantity,Sales_Amount,Payment_Method,Order_Status
0,ORD1001,Kavya,Chennai,Electronics,Laptop,2026-02-05,3,165000.0,UPI,Cancelled
1,ORD1002,Aarav,Vijayawada,Electronics,Mouse,2026-02-25,1,700.0,Credit Card,Cancelled
2,ORD1003,Arjun,Kolkata,Groceries,Rice,2026-04-18,5,3500.0,Credit Card,Pending
3,ORD1004,Sneha,Mumbai,Groceries,Biscuits,2026-03-29,1,120.0,Debit Card,Delivered
4,ORD1005,Rahul,Mumbai,Furniture,Bookshelf,2026-01-25,1,5000.0,Debit Card,Delivered

===== LAST 5 ROWS =====

,Order_ID,Customer_Name,City,Category,Product,Order_Date,Quantity,Sales_Amount,Payment_Method,Order_Status
495,ORD1496,Divya,Bengaluru,Furniture,Chair,2026-04-18,4,14000.0,Cash,Pending
496,ORD1497,Kavya,Kolkata,Electronics,Headphones,2026-06-13,3,7500.0,Cash,Delivered
497,ORD1498,Ishita,Hyderabad,Groceries,Biscuits,2026-03-17,2,240.0,UPI,Pending
498,ORD1499,Sneha,Pune,Furniture,Bookshelf,2026-06-17,5,25000.0,UPI,Delivered
499,ORD1500,Pooja,Pune,Clothing,Jeans,2026-04-06,3,5400.0,Debit Card,Cancelled

===== DATASET INFORMATION =====
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        500 non-null    object
 1   Customer_Name   492 non-null    object
 2   City            493 non-null    object
 3   Category        500 non-null    object
 4   Product         500 non-null    object
 5   Order_Date      500 non-null    object
 6   Quantity        500 non-null    int64
 7   Sales_Amount    495 non-null    float64
 8   Payment_Method  494 non-null    object
 9   Order_Status    500 non-null    object
dtypes: float64(1), int64(1), object(8)
memory usage: 39.2+ KB

In [ ]:
# STEP 3: CHECK DATA QUALITY

print("===== MISSING VALUES =====")
print(df.isnull().sum())

print("\n===== DUPLICATE ROWS =====")
print("Number of duplicate rows:", df.duplicated().sum())

print("\n===== UNIQUE VALUES IN EACH COLUMN =====")
for column in df.columns:
    print(f"\n{column}:")
    print(df[column].unique()[:20])

===== MISSING VALUES =====
Order_ID          0
Customer_Name     8
City              7
Category          0
Product           0
Order_Date        0
Quantity          0
Sales_Amount      5
Payment_Method    6
Order_Status      0
dtype: int64

===== DUPLICATE ROWS =====
Number of duplicate rows: 0

===== UNIQUE VALUES IN EACH COLUMN =====

Order_ID:
['ORD1001' 'ORD1002' 'ORD1003' 'ORD1004' 'ORD1005' 'ORD1006' 'ORD1007'
 'ORD1008' 'ORD1009' 'ORD1010' 'ORD1011' 'ORD1012' 'ORD1013' 'ORD1014'
 'ORD1015' 'ORD1016' 'ORD1017' 'ORD1018' 'ORD1019' 'ORD1020']

Customer_Name:
['Kavya' 'Aarav' 'Arjun' 'Sneha' 'Rahul' 'Sanjay' 'Meera' 'Ananya'
 'Nikhil' 'Vikram' 'Kiran' 'Priya' 'Ishita' 'Varun' 'Aditya' 'Neha'
 'Pooja' 'Rohan' 'Divya' nan]

City:
['Chennai' 'Vijayawada' 'Kolkata' 'Mumbai' 'Visakhapatnam' 'chennai'
 'Hyderabad' 'Pune' 'Bengaluru' 'Guntur' 'Delhi' nan 'delhi'
 'visakhapatnam' 'kolkata' 'bengaluru' 'pune' 'guntur' 'mumbai'
 'vijayawada']

Category:
['Electronics' 'Groceries' 'Furniture' 'Clothing' 'Books' 'FURNITURE'
 'CLOTHING' 'GROCERIES' 'BOOKS']

Product:
['Laptop' 'Mouse' 'Rice' 'Biscuits' 'Bookshelf' 'Jeans' 'Coffee' 'T-Shirt'
 'Textbook' 'Cooking Oil' 'Novel' 'Shoes' 'Chair' 'Headphones' 'Comics'
 'Desk' 'Table' 'Jacket' 'Notebook' 'Keyboard']

Order_Date:
['2026-02-05' '2026-02-25' '2026-04-18' '2026-03-29' '2026-01-25'
 '2026-02-01' '2026-02-19' '2026-04-08' '2026-06-21' '2026-04-29'
 '2026-01-09' '2026-02-24' '2026-05-24' '2026-02-26' '2026-06-10'
 '2026-04-30' '2026-06-14' '2026-03-09' '2026-02-20' '2026-01-05']

Quantity:
[3 1 5 2 4]

Sales_Amount:
[1.65e+05 7.00e+02 3.50e+03 1.20e+02 5.00e+03 6.00e+02 5.40e+03 2.25e+03
 1.35e+03 1.80e+03 2.70e+03 9.00e+02 5.00e+02 2.80e+03 2.10e+03 1.75e+04
 3.60e+02 3.00e+02 3.50e+04 5.50e+04]

Payment_Method:
['UPI' 'Credit Card' 'Debit Card' 'Cash' 'Net Banking' nan ' Debit Card '
 ' Cash ' ' Credit Card ' ' UPI ' ' Net Banking ']

Order_Status:
['Cancelled' 'Pending' 'Delivered']

In [ ]:
# STEP 4: CHECK DATA TYPES AND VALUES

print("===== DATA TYPES =====")
print(df.dtypes)

print("\n===== QUANTITY VALUES =====")
print(df["Quantity"].unique())

print("\n===== SALES AMOUNT VALUES =====")
print(df["Sales_Amount"].unique()[:20])

print("\n===== ORDER DATE VALUES =====")
print(df["Order_Date"].head(10))

===== DATA TYPES =====
Order_ID           object
Customer_Name      object
City               object
Category           object
Product            object
Order_Date         object
Quantity            int64
Sales_Amount      float64
Payment_Method     object
Order_Status       object
dtype: object

===== QUANTITY VALUES =====
[3 1 5 2 4]

===== SALES AMOUNT VALUES =====
[1.65e+05 7.00e+02 3.50e+03 1.20e+02 5.00e+03 6.00e+02 5.40e+03 2.25e+03
 1.35e+03 1.80e+03 2.70e+03 9.00e+02 5.00e+02 2.80e+03 2.10e+03 1.75e+04
 3.60e+02 3.00e+02 3.50e+04 5.50e+04]

===== ORDER DATE VALUES =====
0    2026-02-05
1    2026-02-25
2    2026-04-18
3    2026-03-29
4    2026-01-25
5    2026-02-01
6    2026-02-19
7    2026-04-08
8    2026-06-21
9    2026-04-29
Name: Order_Date, dtype: object

In [ ]:
# STEP 5: DATA CLEANING

# 1. Remove duplicate rows
df = df.drop_duplicates()

# 2. Remove extra spaces from text columns
text_columns = df.select_dtypes(include="object").columns

for column in text_columns:
    df[column] = df[column].str.strip()

# 3. Standardize text capitalization
for column in text_columns:
    df[column] = df[column].str.title()

# 4. Convert Quantity to numeric
df["Quantity"] = pd.to_numeric(df["Quantity"], errors="coerce")

# 5. Convert Sales_Amount to numeric
df["Sales_Amount"] = pd.to_numeric(df["Sales_Amount"], errors="coerce")

# 6. Convert Order_Date to date format
df["Order_Date"] = pd.to_datetime(df["Order_Date"], errors="coerce")

# 7. Handle missing values
df["Customer_Name"] = df["Customer_Name"].fillna("Unknown")
df["City"] = df["City"].fillna("Unknown")
df["Category"] = df["Category"].fillna("Unknown")
df["Product"] = df["Product"].fillna("Unknown")
df["Payment_Method"] = df["Payment_Method"].fillna("Unknown")
df["Order_Status"] = df["Order_Status"].fillna("Unknown")

# Display cleaned dataset
print("Data cleaning completed!")
display(df.head())

Data cleaning completed!

,Order_ID,Customer_Name,City,Category,Product,Order_Date,Quantity,Sales_Amount,Payment_Method,Order_Status
0,Ord1001,Kavya,Chennai,Electronics,Laptop,2026-02-05,3,165000.0,Upi,Cancelled
1,Ord1002,Aarav,Vijayawada,Electronics,Mouse,2026-02-25,1,700.0,Credit Card,Cancelled
2,Ord1003,Arjun,Kolkata,Groceries,Rice,2026-04-18,5,3500.0,Credit Card,Pending
3,Ord1004,Sneha,Mumbai,Groceries,Biscuits,2026-03-29,1,120.0,Debit Card,Delivered
4,Ord1005,Rahul,Mumbai,Furniture,Bookshelf,2026-01-25,1,5000.0,Debit Card,Delivered

In [ ]:
# STEP 6: VALIDATE CLEANED DATA

print("===== DATASET SHAPE =====")
print("Rows and Columns:", df.shape)

print("\n===== MISSING VALUES =====")
print(df.isnull().sum())

print("\n===== DUPLICATE ROWS =====")
print("Duplicate rows:", df.duplicated().sum())

print("\n===== DATA TYPES =====")
print(df.dtypes)

print("\n===== SAMPLE OF CLEANED DATA =====")
display(df.head())

===== DATASET SHAPE =====
Rows and Columns: (500, 10)

===== MISSING VALUES =====
Order_ID          0
Customer_Name     0
City              0
Category          0
Product           0
Order_Date        0
Quantity          0
Sales_Amount      5
Payment_Method    0
Order_Status      0
dtype: int64

===== DUPLICATE ROWS =====
Duplicate rows: 0

===== DATA TYPES =====
Order_ID                  object
Customer_Name             object
City                      object
Category                  object
Product                   object
Order_Date        datetime64[ns]
Quantity                   int64
Sales_Amount             float64
Payment_Method            object
Order_Status              object
dtype: object

===== SAMPLE OF CLEANED DATA =====

,Order_ID,Customer_Name,City,Category,Product,Order_Date,Quantity,Sales_Amount,Payment_Method,Order_Status
0,Ord1001,Kavya,Chennai,Electronics,Laptop,2026-02-05,3,165000.0,Upi,Cancelled
1,Ord1002,Aarav,Vijayawada,Electronics,Mouse,2026-02-25,1,700.0,Credit Card,Cancelled
2,Ord1003,Arjun,Kolkata,Groceries,Rice,2026-04-18,5,3500.0,Credit Card,Pending
3,Ord1004,Sneha,Mumbai,Groceries,Biscuits,2026-03-29,1,120.0,Debit Card,Delivered
4,Ord1005,Rahul,Mumbai,Furniture,Bookshelf,2026-01-25,1,5000.0,Debit Card,Delivered

In [ ]:
# STEP 7: HANDLE MISSING SALES AMOUNTS

# Calculate the median sales amount
median_sales = df["Sales_Amount"].median()

print("Median Sales Amount:", median_sales)

# Fill missing Sales_Amount values with the median
df["Sales_Amount"] = df["Sales_Amount"].fillna(median_sales)

print("\nMissing Sales Amounts after cleaning:",
      df["Sales_Amount"].isnull().sum())

Median Sales Amount: 3500.0

Missing Sales Amounts after cleaning: 0

In [ ]:
# STEP 8: FINAL VALIDATION

print("===== FINAL DATASET CHECK =====")

print("\nShape:")
print(df.shape)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())

print("\nData Types:")
print(df.dtypes)

print("\nFinal 5 Rows:")
display(df.tail())

===== FINAL DATASET CHECK =====

Shape:
(500, 10)

Missing Values:
Order_ID          0
Customer_Name     0
City              0
Category          0
Product           0
Order_Date        0
Quantity          0
Sales_Amount      0
Payment_Method    0
Order_Status      0
dtype: int64

Duplicate Rows:
0

Data Types:
Order_ID                  object
Customer_Name             object
City                      object
Category                  object
Product                   object
Order_Date        datetime64[ns]
Quantity                   int64
Sales_Amount             float64
Payment_Method            object
Order_Status              object
dtype: object

Final 5 Rows:

,Order_ID,Customer_Name,City,Category,Product,Order_Date,Quantity,Sales_Amount,Payment_Method,Order_Status
495,Ord1496,Divya,Bengaluru,Furniture,Chair,2026-04-18,4,14000.0,Cash,Pending
496,Ord1497,Kavya,Kolkata,Electronics,Headphones,2026-06-13,3,7500.0,Cash,Delivered
497,Ord1498,Ishita,Hyderabad,Groceries,Biscuits,2026-03-17,2,240.0,Upi,Pending
498,Ord1499,Sneha,Pune,Furniture,Bookshelf,2026-06-17,5,25000.0,Upi,Delivered
499,Ord1500,Pooja,Pune,Clothing,Jeans,2026-04-06,3,5400.0,Debit Card,Cancelled

In [ ]:
# STEP 9: SAVE COMPLETE CLEANED DATASET

# Save the cleaned dataset as a new CSV file
cleaned_file = "CodeOrbit_Task1_Cleaned_Dataset.csv"

df.to_csv(cleaned_file, index=False)

print("Cleaned dataset saved successfully!")
print("File name:", cleaned_file)
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Cleaned dataset saved successfully!
File name: CodeOrbit_Task1_Cleaned_Dataset.csv
Rows: 500
Columns: 10

In [ ]:
from google.colab import files

files.download("CodeOrbit_Task1_Cleaned_Dataset.csv")